init:
  - git config --global core.autocrlf input

shallow_clone: true

version: '{build}'

environment:
  matrix:
    - nodejs_version: '0.10'
    - nodejs_version: '0.11'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g mocha
  - npm install

build: off

test_script:
  - ps: '_mocha test.js #PowerShell'
  - cmd: _mocha test.js

cache:
  - node_modules
