init:
  - git config --global core.autocrlf input

shallow_clone: true

version: '{build}'

skip_tags: true

environment:
  matrix:
    - nodejs_version: '1'
    - nodejs_version: '0.12'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

test_script:
  - ps: 'npm run-script test-dot #PowerShell'
  - cmd: npm run-script test-dot

cache:
  - node_modules -> package.json
